import http from "http";
import { AddressInfo } from "net";
import { afterAll, beforeAll, describe, expect, it, vi } from "vitest";

vi.mock("./retrieval/discussion", () => ({ searchDiscussion: async () => ({ snippets: [], skipped: [], searched: ["test"] }) }));
import { runPipeline } from "./pipeline";
import { KitSchema } from "./kit-schema";
import type { LlmClient } from "./llm";

const JD = `Backend Engineer at Acme\n\nRequirements:\n- Strong TypeScript\n- PostgreSQL experience\n- Mentoring other engineers\n\nNice to have:\n- Kafka`;

/** Fake model: covers only the first requirement it is given, so the coverage loop has real gaps to close. */
function fakeLlm(): LlmClient & { labels: string[] } {
  const labels: string[] = [];
  return {
    labels,
    json: async ({ label, user, schema }) => schema.parse(respond(label, user)),
  };
  function respond(label: string, user: string): any {
      labels.push(label);
      if (label === "extract requirements") return {
        company: "Acme", title: "Backend Engineer", seniority: "mid", location: "Remote", responsibilities: ["Build APIs"],
        requirements: [
          { text: "TypeScript", quote: "Strong TypeScript", kind: "technical", priority: "must" },
          { text: "PostgreSQL", quote: "PostgreSQL experience", kind: "technical", priority: "must" },
          { text: "Mentoring", quote: "Mentoring other engineers", kind: "behavioural", priority: "must" },
          { text: "Kafka", quote: "Kafka", kind: "technical", priority: "must" },
        ],
      } as any;
      if (label === "company brief") return { company_name: "Acme", summary: "Acme makes APIs.", what_they_do: "APIs", interview_process: [] } as any;
      const ids = [...user.matchAll(/\b(r\d+) \(/g)].map((m) => m[1]);
      const must = user.match(/must be covered by at least one question: ([^.]+)\./)?.[1].split(", ") ?? [];
      const cover = must.length ? must : ids.slice(0, 1);
      return { questions: cover.length ? cover.map((id, i) => ({ prompt: `${label} ${id} ${i} ${labels.length}`, answer_outline: "points", difficulty: 3, requirement_ids: [id] }))
        : [{ prompt: `${label} general`, answer_outline: "points", difficulty: 1, requirement_ids: [] }] };
  }
}

let server: http.Server, base = "";
beforeAll(async () => {
  server = http.createServer((req, res) => {
    if (req.url === "/acme/") { res.writeHead(200, { "content-type": "text/html" }); return res.end(`<title>Acme</title><main><p>Acme makes APIs for developers across the world, every day.</p></main>`); }
    res.writeHead(404); res.end();
  });
  await new Promise<void>((r) => server.listen(0, "127.0.0.1", r));
  base = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  process.env.CRAWL_DELAY_MS = "0";
});
afterAll(() => server.close());

describe("runPipeline", () => {
  it("produces a valid kit with every must-have covered and the requested number of days", async () => {
    const llm = fakeLlm();
    const steps: string[] = [];
    const { kit } = await runPipeline({ jd: JD, company_url: `${base}/acme/`, days: 4 }, (s) => { steps.push(s); }, llm);
    expect(KitSchema.safeParse(kit).success).toBe(true);
    expect(kit.role.requirements.find((r) => r.text === "Kafka")?.priority).toBe("nice");
    expect(kit.coverage.uncovered_requirement_ids).toEqual([]);
    expect(kit.coverage.passes).toBeGreaterThanOrEqual(2);            // the draft left gaps, so a second pass ran
    expect(kit.schedule.days).toHaveLength(4);
    // categories are generated by separate calls
    expect(llm.labels.filter((l) => l.endsWith("questions")).length).toBeGreaterThanOrEqual(3);
    expect(kit.notes?.some((n) => /No hiring/.test(n))).toBe(true);
  });

  it("still builds an honest kit when the company site is unreachable", async () => {
    const { kit } = await runPipeline({ jd: JD, company_url: `${base}/nothing-here/`, days: 1 }, () => {}, fakeLlm());
    expect(kit.source.pages_used).toEqual([]);
    expect(kit.company_brief.summary).toMatch(/could not retrieve/i);
    expect(kit.schedule.days).toHaveLength(1);
  });
});
